### ISSUE TITLE
Suggestion: Preprocess more than one column at the same time

### ISSUE THREAD

**Issue by luisferreira97** [Metalkiler/Cane-Categorical-Attribute-traNsformation-Environment#1]
It could be a good feature to allow to pass as an argument a list of columns to preprocess.

Example: 
dataIDF = cane.idf(df, columns = ["colA", "colB", "colC"])

This would apply IDF to colA, colB and colC. The same could be applied to PCP and One-Hot

**Comment by Metalkiler** [comment]
Good Suggestion! Dealing with the issue as Quick as possible!

**Comment by Metalkiler** [comment]
New Version updated based on this issue!

Thanks for the suggestion!

please download the new Version at https://pypi.org/project/cane/

or

pip Install cane --upgrade
