### ISSUE TITLE
Suggestion: "Multi-column" PCP/IDF

### ISSUE THREAD

**Issue by luisferreira97** [Metalkiler/Cane-Categorical-Attribute-traNsformation-Environment#2]
There could be multi-column processing, to ensure a consistent mapping between different columns of the same type. For example, if I have columns "CityA" and "CityB" for each record, I might want to consider all the cities from both columns. The goal is that a city that is considered "Others" in "CityA" is also "Others" on "CityB".

Example:
dataIDF = cane.idf(df, multiCol = True, multColumns = ["colA", "colB"])

This would apply the "multi-column" IDF to colA, colB. (There could be a similiar approach to PCP and One-Hot)

**Comment by Metalkiler** [comment]
So the ideia is to agreggate the values from A and B into a new Column (C) and apply that transformation into (C)?

**Comment by luisferreira97** [comment]
Yes, but the final dataset would have cols A and B (not a new column C). Basically the col C would be used to create the common mappings

**Comment by Metalkiler** [comment]
So basically the C column is the "dictionary" for the divided column
Got it!

Although you could merge both values City A and B into a new column and erase the previous ones 
But I will see what I can do!

Thanks for the suggestion!

**Comment by Metalkiler** [comment]
Hi again, launched a beta Version in Pypi with that feedback

to Install you can run pip install cane==0.0.1.7.7b0

Check GitHub for examples!


Best Regards

**Comment by Metalkiler** [comment]
Following the final tests this functionality is now implemented correctly! Update your Cane Version and check the exemple!
